### PR TITLE
Commit doc updates from main

### PR DESCRIPTION
**Pull request by emilyJLin95**

### CODE REVIEW

**Comment by emilyJLin95** [comment]
@fainashalts is there an ability for us to change master over to main? so we don't have to do this double PR

**Comment by fainashalts** [comment]
@emilyJLin95 not until there's a fix in the unbox code to cover both names. @cds-amal was looking at this at some point.

**Review by fainashalts — APPROVED** [review]
LGTM!

**Comment by fainashalts** [comment]
> @fainashalts is there an ability for us to change master over to main? so we don't have to do this double PR

I would love to do that, but I believe something needs to be changed in the code that unboxes the boxes first. I think @cds-amal was looking into it.

**Pull request merged**
